# Generated by Django 5.0.6 on 2024-08-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBio',
            fields=[
                ('user_id', models.CharField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
            ],
        ),
    ]
