from django.db import models 

'''
UserBio: Is a model that maps to a single database table
Each attribute of the model represents a database field 

The model below will create a database table like this...

CREATE TABLE UserBio(
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
    "user_email" varchar(50) NOT NULL,
    "user_name" varchar(30) NOT NULL,
    "first_name" varchar(30) NOT NULL,
    "last_name" varchar(30) NOT NULL,
    "company" varchar(30) NOT NULL,
)

'''
class UserBio(models.Model):
    user_id = models.ForeignKey(unique=True) 
    user_email = models.CharField(max_length=50)
    user_name = models.CharField(max_length=30)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    company = models.CharField(max_length=30)
    
    def __str__(self) -> str:
        return self.user_name