from django.db import models 
from django.contrib.auth.models import User

'''
UserAccount: Is a model that maps to a single database table
Each attribute of the model represents a database field 

The model below will create a database table like this...

CREATE TABLE UserAccount(
    "user_id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
    "user_email" varchar(50) NOT NULL,
    "user_name" varchar(30) NOT NULL,
    "first_name" varchar(30) NOT NULL,
    "last_name" varchar(30) NOT NULL,
    "company" varchar(30) NOT NULL,
)

@Type: (One-to-One)

@Notes: user_id is the primary key linking UserAccount, directly to User

@Relevant Sources: https://docs.djangoproject.com/en/5.0/topics/db/models/#automatic-primary-key-fields
'''
class UserAccount(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True) # Made as primary key, and will auto-increment
    user_email = models.CharField(max_length=50)
    user_name = models.CharField(max_length=30)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    company = models.CharField(max_length=30)
    
    def __str__(self) -> str:
        return self.user_name