# Generated by Django 5.0.6 on 2024-06-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=4)),
                ('last', models.IntegerField()),
                ('bid', models.IntegerField()),
                ('ask', models.IntegerField()),
                ('change', models.IntegerField()),
                ('change_percent', models.IntegerField()),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
