# Generated by Django 5.0.6 on 2024-08-02 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userbiography', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=4, unique=True)),
                ('last', models.DecimalField(decimal_places=2)),
                ('open', models.DecimalField(decimal_places=2)),
                ('high', models.DecimalField(decimal_places=2)),
                ('low', models.DecimalField(decimal_places=2)),
                ('change_percent', models.DecimalField(decimal_places=2)),
                ('volume', models.DecimalField(decimal_places=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userbiography.userbio')),
            ],
        ),
    ]
